org: jvictor940
app: blk-letics
service: blk-letics
frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'
  tableNameAthlete: 'athletes-table-${sls:stage}'
  tableNameUniversity: 'university-table-${sls:stage}'

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
            - Fn::GetAtt: [ AthletesTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}
    ATHLETES_TABLE: ${self:custom.tableNameAthlete}
    # UNIVERSITIES_TABLE: ${self:custom.tableNameUniversity}
# plugins:
#   - serverless plugin install -n serverless-github-action@v3.2

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
  athlete:
    handler: athlete.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

    AthletesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: athleteId
            AttributeType: S
        KeySchema:
          - AttributeName: athleteId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameAthlete}

    UniversityTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: universityId
            AttributeType: S
        KeySchema:
          - AttributeName: universityId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameUniversity}
